name: "Add Reviewers to PR"
on:
  pull_request:
    types:
      - opened
jobs:
  call_me_may:
    runs-on: ubuntu-latest
    name: Add reviewers
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add reviewers step
        uses: zenger-tester/Action-PR-Reviewers-Update/.github/workflows/main.yml@main
        with:
          reviewers: "ZengerU"
          reviewer_teams: "game-dev"
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.PAT }}
          